"""init_4

Revision ID: 20260429152314
Revises: f01240ad48cd
Create Date: 2026-04-29 15:23:18.226778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260429152314'
down_revision: Union[str, Sequence[str], None] = 'f01240ad48cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elo_history', sa.Column('chips_bonus', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('elo_history', 'chips_bonus')
    # ### end Alembic commands ###
