"""init_2

Revision ID: 20260427175319
Revises: 
Create Date: 2026-04-27 17:53:22.227814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260427175319'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('elo', sa.Float(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_index(op.f('ix_players_is_archived'), 'players', ['is_archived'], unique=False)
    op.create_index(op.f('ix_players_telegram_id'), 'players', ['telegram_id'], unique=True)
    op.create_table('telegram_chats',
    sa.Column('activator_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('thread_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_title', sa.String(), nullable=False),
    sa.Column('owner_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activator_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_index(op.f('ix_telegram_chats_activator_id'), 'telegram_chats', ['activator_id'], unique=False)
    op.create_index(op.f('ix_telegram_chats_chat_id'), 'telegram_chats', ['chat_id'], unique=False)
    op.create_table('games',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('AWAITED', 'IN_ACTION', 'CANCELED', 'FINISHED', name='game_status'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organizer_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['telegram_chat_id'], ['telegram_chats.chat_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_index(op.f('ix_games_is_archived'), 'games', ['is_archived'], unique=False)
    op.create_index(op.f('ix_games_organizer_id'), 'games', ['organizer_id'], unique=False)
    op.create_table('game_players',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('JOINED', 'LEFT', name='game_player_status'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'game_id')
    )
    op.create_index(op.f('ix_game_players_id'), 'game_players', ['id'], unique=False)
    op.create_table('tables',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'number', 'round')
    )
    op.create_index(op.f('ix_tables_id'), 'tables', ['id'], unique=False)
    op.create_table('elo_history',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('elo_before', sa.Float(), nullable=False),
    sa.Column('elo_after', sa.Float(), nullable=False),
    sa.Column('elo_change', sa.Float(), nullable=True),
    sa.Column('bounty_bonus', sa.Float(), nullable=True),
    sa.Column('players_total', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('chips', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elo_history_game_id'), 'elo_history', ['game_id'], unique=False)
    op.create_index(op.f('ix_elo_history_id'), 'elo_history', ['id'], unique=False)
    op.create_index(op.f('ix_elo_history_player_id'), 'elo_history', ['player_id'], unique=False)
    op.create_index(op.f('ix_elo_history_table_id'), 'elo_history', ['table_id'], unique=False)
    op.create_table('table_players',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('chips', sa.Integer(), nullable=False),
    sa.Column('eliminated_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['eliminated_by_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id', 'player_id')
    )
    op.create_index(op.f('ix_table_players_id'), 'table_players', ['id'], unique=False)
    op.create_index(op.f('ix_table_players_player_id'), 'table_players', ['player_id'], unique=False)
    op.create_index(op.f('ix_table_players_table_id'), 'table_players', ['table_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_table_players_table_id'), table_name='table_players')
    op.drop_index(op.f('ix_table_players_player_id'), table_name='table_players')
    op.drop_index(op.f('ix_table_players_id'), table_name='table_players')
    op.drop_table('table_players')
    op.drop_index(op.f('ix_elo_history_table_id'), table_name='elo_history')
    op.drop_index(op.f('ix_elo_history_player_id'), table_name='elo_history')
    op.drop_index(op.f('ix_elo_history_id'), table_name='elo_history')
    op.drop_index(op.f('ix_elo_history_game_id'), table_name='elo_history')
    op.drop_table('elo_history')
    op.drop_index(op.f('ix_tables_id'), table_name='tables')
    op.drop_table('tables')
    op.drop_index(op.f('ix_game_players_id'), table_name='game_players')
    op.drop_table('game_players')
    op.drop_index(op.f('ix_games_organizer_id'), table_name='games')
    op.drop_index(op.f('ix_games_is_archived'), table_name='games')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_telegram_chats_chat_id'), table_name='telegram_chats')
    op.drop_index(op.f('ix_telegram_chats_activator_id'), table_name='telegram_chats')
    op.drop_table('telegram_chats')
    op.drop_index(op.f('ix_players_telegram_id'), table_name='players')
    op.drop_index(op.f('ix_players_is_archived'), table_name='players')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
