"""init_3

Revision ID: 20260427221342
Revises: 20260427175319
Create Date: 2026-04-27 22:13:46.339818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260427221342'
down_revision: Union[str, Sequence[str], None] = '20260427175319'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_chats', 'owner_telegram_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_chats', sa.Column('owner_telegram_id', sa.BIGINT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
